export const TEMP_EMAIL = 'TEMP_EMAIL'
export const REGISTER_USER = 'REGISTER_USER'
export const LOAD_USER = 'LOAD_USER'
export const LOGOUT_USER = 'LOGOUT_USER'
export const USER_ERROR = 'USER_ERROR'
export const ADD_PROFILE = 'ADD_PROFILE'
export const SELECT_PROFILE = 'SELECT_PROFILE'
